dist: trusty
sudo: false

git:
  depth: 3

language: node_js
node_js:
  - "9"

cache: yarn

install:
  - yarn install

script:
  - cd admin-ui && yarn test --watch=false --browsers=ChromeHeadlessCI --progress=false
  - cd ../server && yarn test
  - yarn test:e2e
  - cd ../admin-ui && yarn build --prod
