dist: trusty
sudo: false

git:
  depth: 3

language: node_js
node_js:
  - "12"

cache: yarn

install:
  - yarn install
  - yarn bootstrap

script:
  - yarn lerna run build
  - yarn test:all
  - cd admin-ui && yarn build --prod
