dist: trusty
sudo: false

git:
  depth: 3

language: node_js
node_js:
  - "10"

cache: yarn

install:
  - yarn install
  - yarn bootstrap && cd ..

script:
  - yarn lerna run build
  - yarn test:all
  - cd admin-ui && yarn build --prod
