baseURL = "http://example.org/"
languageCode = "en-us"
title = "Vendure"
googleAnalytics = "UA-133911942-1"
pygmentsCodeFences = true
pygmentsUseClasses = true
disableKinds = [
  "taxonomy",
  "taxonomyTerm"
]
[params]
    BookSection = "docs"

