baseURL = "http://example.org/"
languageCode = "en-us"
title = "Vendure Documenation"
pygmentsCodeFences = true
disableKinds = [
  "taxonomy",
  "taxonomyTerm"
]
[params]
    BookMenuBundle = "/menu"
    BookSection = "docs"

