baseURL = "http://example.org/"
languageCode = "en-us"
title = "Vendure Documenation"
pygmentsCodeFences = true
pygmentsStyle = "monokai"
disableKinds = [
  "taxonomy",
  "taxonomyTerm"
]
[params]
    BookSection = "docs"

